version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-psa-interview"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-c0hvvcgdo9jm"
s3_prefix = "aws-psa-interview"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "paramEnvironment=\"stage\" paramServiceName=\"psa-interview\" fromMailIdentityName=\"psainterviewfrom@gmail.com\" toMailIdentityName=\"psainterviewto@gmail.com\""
image_repositories = []
