AWSTemplateFormatVersion: 2010-09-09
Description: aws-psa-interview
Transform: AWS::Serverless-2016-10-31

Parameters:
  paramEnvironment:
    Type: String
    AllowedValues:
      - stage
      - prod
    Default: stage
  paramServiceName:
    Type: String
  fromMailIdentityName:
    Type: String
  toMailIdentityName:
    Type: String

Globals:
  Function:
    Layers:
      - !Ref LayerDepencies
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        FAQ_TABLE: !Ref FAQTopicsTable
        EMAIL_TABLE: !Ref EmailSupportTable
        # Reuse connection to DynamoDB to improve response time
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

Resources:
  # API Gateway resource
  FAQApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${paramServiceName}-${paramEnvironment}"
      StageName: !Sub "${paramEnvironment}"
      #EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"
        DefaultAuthorizer: CognitoAuthorizer

  GatewayResponseDefault4XX:
    Type: 'AWS::ApiGateway::GatewayResponse'
    Properties:
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
      ResponseType: DEFAULT_4XX
      RestApiId: !Ref FAQApi

  CreateTopicFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      FunctionName: !Sub "${paramEnvironment}-${paramServiceName}-create-faq"
      Handler: create-topic.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FAQTopicsTable
      Events:
        CreateApiEvent:
          Type: Api 
          Properties:
            Path: /topic
            Method: POST
            RestApiId:
              Ref: FAQApi

  DeleteTopicFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      FunctionName: !Sub "${paramEnvironment}-${paramServiceName}-delete-faq"
      Handler: delete-topic.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FAQTopicsTable
      Events:
        DeleteApiEvent:
          Type: Api 
          Properties:
            Path: /topic/{topic_id}
            Method: DELETE
            RestApiId:
              Ref: FAQApi

  EditTopicFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      FunctionName: !Sub "${paramEnvironment}-${paramServiceName}-edit-faq"
      Handler: edit-topic.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FAQTopicsTable
      Events:
        EditApiEvent:
          Type: Api 
          Properties:
            Path: /topic/{topic_id}
            Method: PUT
            RestApiId:
              Ref: FAQApi

  GetTopicFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      FunctionName: !Sub "${paramEnvironment}-${paramServiceName}-get-faq"
      Handler: get-topic.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FAQTopicsTable
      Events:
        GetApiEvent:
          Type: Api 
          Properties:
            Path: /topic/{topic_id}
            Method: GET
            RestApiId:
              Ref: FAQApi
            Auth:
              Authorizer: NONE
  
  ListTopicsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      FunctionName: !Sub "${paramEnvironment}-${paramServiceName}-list-faq"
      Handler: list-topics.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FAQTopicsTable
      Events:
        ListApiEvent:
          Type: Api 
          Properties:
            Path: /topics
            Method: GET
            RestApiId:
              Ref: FAQApi
            Auth:
              Authorizer: NONE

  RegisterEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: !Sub "${paramEnvironment}-${paramServiceName}-register-email"
      Handler: register-email.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EmailSupportTable
      Events:
        ListApiEvent:
          Type: Api 
          Properties:
            Path: /message
            Method: POST
            RestApiId:
              Ref: FAQApi
            Auth:
              Authorizer: NONE

  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      FunctionName: !Sub "${paramEnvironment}-${paramServiceName}-send-email"
      Handler: send-email.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - SESCrudPolicy:
            IdentityName: !Ref fromMailIdentityName
        - SESCrudPolicy:
            IdentityName: !Ref toMailIdentityName
      Environment:
        Variables:
          FROM_EMAIL: !Ref fromMailIdentityName
          TO_EMAIL: !Ref toMailIdentityName
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt EmailSupportTable.StreamArn
            BatchSize: 1
            StartingPosition: LATEST

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameConfiguration: 
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UserPoolName: !Sub "${paramEnvironment}-${paramServiceName}-user-pool"
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:3001
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${paramServiceName}-${paramEnvironment}"
      UserPoolId: !Ref UserPool
      
  # Creates a federeated Identity pool
  IdentityPool:
    Type: "AWS::Cognito::IdentityPool"
    Properties:
      IdentityPoolName: !Sub "${paramServiceName}-${paramEnvironment}-identity-pool"
      AllowUnauthenticatedIdentities: true
      CognitoIdentityProviders: 
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  # Create a role for unauthorized acces to AWS resources. 
  # Very limited access. Only allows users in the previously created Identity Pool
  CognitoUnAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              Federated: "cognito-identity.amazonaws.com"
            Action: 
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals: 
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: "CognitoUnauthorizedPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                Resource: "*"

  # Create a role for authorized acces to AWS resources. 
  # Control what your user can access. This example only allows Lambda invokation
  # Only allows users in the previously created Identity Pool
  CognitoAuthorizedRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              Federated: "cognito-identity.amazonaws.com"
            Action: 
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals: 
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": authenticated
      Policies:
        - PolicyName: "CognitoAuthorizedPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action:
                  - "mobileanalytics:PutEvents"
                  - "cognito-sync:*"
                  - "cognito-identity:*"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "execute-api:Invoke"
                Resource: !Sub "arn:aws:execute-api:${AWS::Region}:*:${FAQApi}/*/*/*"
    
  # Assigns the roles to the Identity Pool
  IdentityPoolRoleMapping:
    Type: "AWS::Cognito::IdentityPoolRoleAttachment"
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt "CognitoAuthorizedRole.Arn"
        unauthenticated: !GetAtt "CognitoUnAuthorizedRole.Arn"


  FAQTopicsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FAQ_TOPICS_TABLE
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: topic_id
          AttributeType: S
      KeySchema:
        - AttributeName: topic_id
          KeyType: HASH

  EmailSupportTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EMAIL_SUPPORT_TABLE
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: message_id
          AttributeType: S
      KeySchema:
        - AttributeName: message_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  LayerDepencies:
    Type: AWS::Serverless::LayerVersion
    LayerName: !Sub "${paramEnvironment}-${paramServiceName}-layerDependecies"
    Properties:
      LayerName: OetcardDependencies
      ContentUri: layers/dependencies/.
      CompatibleRuntimes:
        - nodejs14.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: nodejs14.x

Outputs:
  CognitoID:
    Description: The Cognito UserPool ID
    Value: !Ref UserPool
  CognitoClientID:
    Description: The Cognito UserPool Client ID
    Value: !Ref UserPoolClient
  IdentityPoolID:
    Description: The Cognito IdentityPool ID
    Value: !Ref IdentityPool
  ApiEndpoint:
    Description: "API Gateway orginal endpoint URL"
    Value: !Sub "https://${FAQApi}.execute-api.${AWS::Region}.amazonaws.com/${paramEnvironment}"
